### ISSUE TITLE
tinygo GBA

### ISSUE THREAD

**Issue by navossoc** [conejoninja/talks#1]
Hi, I saw your talk on FOSDEM over the internet and I was quite interested about the GBA rom that you compiled and displayed.
I have one (GBA) on my drawer that I can put it to some use.

Is that source available somewhere?
Maybe you can share a a simple hello world just to see how it works.

It will be really helpful.

Thanks.

**Comment by conejoninja** [comment]
Hello,

Links for everything are in the last two slides, for the gba I used this demo : https://github.com/conejoninja/gbatest
You need to build the .gba file and then put it in your gba, usually using a special cartridge (supercard, ezflash iv, omega,...) each cartridge has its own instructions. mGBA emulator works fine.

Please, we warned that GBA support is experimental (not everything is supported yet) , there are a few branches and PR done, ready to be merged or already merged (sorry I can't keep track of all of them).

**Comment by navossoc** [comment]
Yes! There is a page for links, but there are two pages for links 😝 
I must be very tired and just not realizing it.

Sorry about that.
